local opt = vim.opt

opt.number = true
opt.autoread = true
opt.expandtab = true
opt.tabstop = 4
opt.softtabstop = 4
opt.shiftwidth = 4
opt.relativenumber = true
opt.clipboard = "unnamedplus"
opt.virtualedit = "block"
opt.wrap = false
opt.scrolloff = 25
opt.termguicolors = true
opt.backup = false
opt.conceallevel = 0
opt.swapfile = false
opt.smartindent = true
opt.autoindent = true
opt.undofile = true
opt.signcolumn = "yes"
opt.splitbelow = true
opt.splitright = true
