"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3
enable_cursor_positioning = true

[transient_prompt]
newline = true
background = "transparent"
foreground = "p:white"
template = "❯ "

[palette]
red = "#FF0000"
green = "#00FF00"
white = "#FFFFFF"
black = "#000000"
blue = "#0000FF"
yellow = "#FFFF00"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

    [[blocks.segments]]
    style = "plain"
    type = "os"
    background = "transparent"
    foreground = "p:white"

    [[blocks.segments]]
    template = "  {{ path .Path .Location }} "
    type = "path"
    style = "diamond"
    leading_diamond = "<transparent>"
    trailing_diamond = ""
    foreground = "p:white"
    background = "p:blue"

        [blocks.segments.properties]
        max_depth = 3
        style = "agnoster_short"

    [[blocks.segments]]
    type = "git"
    style = "powerline"
    powerline_symbol = ""
    foreground = "p:black"
    background = "p:yellow"
    template = " {{ .UpstreamIcon }} {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{end}}{{if .Working.Changed }} {{.Working.String }}{{ end }} {{if .Staging.Changed }}{{ .Staging.String }}{{ end }}"

        [blocks.segments.properties]
        branch_icon =""
        fetch_status = true
        fetch_upstream_icon = true

[[blocks]]
type = "prompt"
alignment = "right"

    [[blocks.segments]]
    type = "lua"
    style = "plain"
    background = "transparent"
    foreground = "p:blue"
    template = "  "

        [blocks.segments.properties]
        display_mode = 'files'
        fetch_version = false
    
    [[blocks.segments]]
    type = "go"
    style = "plain"
    background = "transparent"
    foreground = "p:blue"
    template = "  "

        [blocks.segments.properties]
        display_mode = 'files'
        fetch_version = false
    
    [[blocks.segments]]
    type = "python"
    style = "plain"
    background = "transparent"
    foreground = "p:yellow"
    template = "  {{ if .Venv }} {{ .Venv }}{{ end }}"

        [blocks.segments.properties]
        display_mode = "context"
        fetch_version = false
        fetch_virtual_env = true

    [[blocks.segments]]
    type = "executiontime"
    style = "plain"
    foreground = "p:white"
    template = " {{ .FormattedMs }} "

        [blocks.segments.properties]
        style = "austin"
        threshold = 1000

[[blocks]]
type = "rprompt"

    [[blocks.segments]]
    type = "time"
    style = "plain"

        [blocks.segments.properties]
        time_format = "_2-Jan-2006 3:04PM"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

    [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground_templates = [
        "{{ if gt .Code 0 }}p:red{{end}}",
        "{{ if eq .Code 0 }}p:green{{end}}",
    ]
    background = "transparent"
    template = "❯"
