export EDITOR="nvim"
export VISUAL="nvim"
export LANG="en_US.UTF-8"   # Sets default locale for all categories
export LC_ALL="en_US.UTF-8" # Overrides all other locale settings
export PATH=$PATH:$HOME/.local/opt/go/bin
export PATH=$PATH:$HOME/go/bin
export PATH=$PATH:$HOME/.local/bin
export MANPAGER="nvim +Man!"
export hoisaves="/home/wesley/.local/share/Paradox Interactive/Hearts of Iron IV/save games"
